name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FRONTEND_IMAGE: mukeshsaini7/bedsheet-frontend
      BACKEND_IMAGE: mukeshsaini7/bedsheet-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ----------------------------
      # Build Frontend
      # ----------------------------
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Frontend
        working-directory: frontend/bedsheet-shop-frontend
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install
          npm install axios
          npm run build

      # ----------------------------
      # Build Backend
      # ----------------------------
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build Backend
        working-directory: backend/product-service
        run: mvn clean package -DskipTests

      # ----------------------------
      # Login to Docker Hub
      # ----------------------------
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # ----------------------------
      # Build and Push Docker Images
      # ----------------------------
      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t $FRONTEND_IMAGE:latest frontend/bedsheet-shop-frontend
          docker push $FRONTEND_IMAGE:latest

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t $BACKEND_IMAGE:latest backend/product-service
          docker push $BACKEND_IMAGE:latest
